name: Deploy to Github Pages
on:
  push:
    branches:
      - master
env:
  VUE_APP_API_KEY: ${{ secrets.VUE_APP_VUE_APP_API_KEY }}
  VUE_APP_AUTH_DOMAIN: ${{ secrets.VUE_APP_AUTH_DOMAIN }}
  VUE_APP_PROJECT_ID: ${{ secrets.VUE_APP_PROJECT_ID }}
  VUE_APP_STORAGE_BUCKET: ${{ secrets.VUE_APP_STORAGE_BUCKET }}
  VUE_APP_MESSAGING_SENDER_ID: ${{ secrets.VUE_APP_MESSAGING_SENDER_ID }}
  VUE_APP_APP_ID: ${{ secrets.VUE_APP_APP_ID }}
  VUE_APP_MEASUREMENT_ID: ${{ secrets.VUE_APP_MEASUREMENT_ID }}

jobs:
  gh-pages-deploy:
    name: Deploying to Github Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install packages
        run: npm i
      - name: Set Creds
        run: git config user.name "Giorgos Tharropoulos" && git config user.email "tharropoulos@gmail.com"
      - name: Deploy
        run: npm run deploy
