name: Deploy to Github Pages
on:
  push:
    branches:
      - master
jobs:
  gh-pages-deploy:
    name: Deploying to Github Pages
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.API_KEY }}
      APP_ID: ${{ secrets.APP_ID }}
      AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }}
      MEASURMENT_ID: ${{ secrets.MEASURMENT_ID }}
      MESSAGING_SENDER_ID: ${{ secrets.MESSAGING_SENDER_ID }}
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install packages
        run: npm i
      - name: Set Creds
        run: git config user.name "Giorgos Tharropoulos" && git config user.email "tharropoulos@gmail.com"
      - name: Deploy
        run: npm run deploy
